# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '>=18.x'
        cache: 'npm'
    - name: Clean install NPM
      run: npm ci
    - name: Run NPM Tests
      run: npm run test -- -u
    
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: '>=18.x'
        cache: 'npm'
    - name: Clean install NPM
      run: npm ci
    - name: BUild Project
      run: npm run build --if-present    
